### PR TITLE
feat: show order ID on carrier

### PR DESCRIPTION
**Pull request by YavorGrancharov**
-   [x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x] Have you explained what your changes do, and why they add value?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

---
Made Order ID visible on Carrier.
e35myp7p9D

### CODE REVIEW

**Comment by evereq** [comment]
@YavorGrancharov you display incorrect order ID. We have more human-readable Order ID (not GUID), you need to display it instead.  See https://github.com/ever-co/ever-docs/blob/master/docs/assets/admin/order/order1.png, you have there "Order 01242019-2" as Order ID

**Comment by YavorGrancharov** [comment]
Fixed by showing the correct ID from the date and not from the DB!
b9u9bDJb5R

**Comment by YavorGrancharov** [comment]
Should I change "Order ID: some ID" with "Order some ID" like on example you provided above?

**Comment by evereq** [comment]
> Should I change "Order ID: some ID" with "Order some ID" like on example you provided above?

no, it's fine like you did now, nothing need to be changed

**Comment by evereq** [comment]
> Fixed by showing the correct ID from the date and not from the DB!
> b9u9bDJb5R

Just one additional question: that value does not strictly date, it included order number (from 1 to how many orders done in that day), so this value DOES come from DB no? At least last part of it :)

**Comment by YavorGrancharov** [comment]
Yes, last part after the dash is order.orderNumber which comes from DB, should I remove it?

**Comment by evereq** [comment]
> Yes, last part after the dash is order.orderNumber which comes from DB, should I remove it?

of course no need to remove, that's actually part of Order ID :D Otherwise all orders in the same day will have same Id :D All is OK now, merging your PR, thanks!

**Pull request merged**
