### PR TITLE
fix: popup on unsuccessfull call us attempt

### PR DESCRIPTION
**Pull request by YavorGrancharov**
-   [x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x] Have you explained what your changes do, and why they add value?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

---
Fixed when Call Us failes to show info popup window to the user! We received the error because the phone number comes from environment!
https://www.loom.com/share/e9327ceecd9e41b7be18627b0e135517

### CODE REVIEW

**Comment by evereq** [comment]
@YavorGrancharov "We received the error because the phone number comes from the environment!" and? You mean that in environment phone number can be not set and so it fails to call or what? I don't really understand..... When it will display such popup you did in this PR? In what cases?

**Comment by YavorGrancharov** [comment]
The function callus() is in try/catch and the popup is in catch clause and the phone number was set like number = environment.NUMBER so when there isn't any number assoiated with the store we show that popup window!

**Comment by evereq** [comment]
@YavorGrancharov yes in does NOT make any logical sense to do it that way :) Was 10 sec to add a check that if phone number not set, we just hide menu item "Call" :) 

However, I think work you did still makes sense, because even if number is set, for some reason could be an issue to try to call it (e.g. something fails) and in such case, your popup could be shown... 

Anyway, always think in a more simple solution first, don't overcomplicate it. Add please a "feature" to hide the Call Us button if the phone number not set in the environment.

**Comment by YavorGrancharov** [comment]
@evereq Made Call Us menu option to not visible when phone number is not set in environment and left popup window to show if there is an error which in our case is (cordova_not_available)!
https://www.loom.com/share/66c8fb4f39ae48989e6c5264561b1271

**Pull request merged**
