### PR TITLE
feat: added flag for cash payment

### PR DESCRIPTION
**Pull request by sunk0**
payment-method

Need to make the interaction with the merchant

### CODE REVIEW

**Comment by evereq** [comment]
@sunk0 such option should be ENABLED by default

**Comment by sunk0** [comment]
@evereq  so what's the option

**Comment by sunk0** [comment]
@evereq i tought it depends who is using it

**Comment by evereq** [comment]
I said default value, do you understand what it means? User can change it, but initially cash payments should be enabled, not disabled

**Comment by sunk0** [comment]
It will be done however you like (fixing tommorow), my bad!

**Comment by sunk0** [comment]
Capturedddd

**Pull request merged**
