### PR TITLE
feat: implemented enable disable store mode

### PR DESCRIPTION
**Pull request by sunk0**
https://www.loom.com/share/c4aae31b00644732a2b0268e1e624a50

What we should do with enabling / disabling all stores? Implementation only for selected store from admin panel.

### CODE REVIEW

**Comment by evereq** [comment]
@sunk0 hm, I doubt you really understand the meaning of that feature "In-Store" mode, if you call it "isStore" in your code...
It's called "In-Store" because it's when customers get "In" store, like "inside" (walk into the doors and sit in the restaurant).

**Comment by sunk0** [comment]
If the logic is wrong, I'm very bad :( @evereq

**Comment by evereq** [comment]
@sunk0 no, it has nothing to do with you being bad or good, just with the fact if you understand feature  you want to improve or not understand....

**Comment by sunk0** [comment]
Is the feature ok, without the naming, if it's not i didn't understood :( ?  @evereq

**Comment by evereq** [comment]
@sunk0 naming is very important, probably the same important as feature itself. In programming how you name things is the most important skill to learn.......

**Comment by sunk0** [comment]
Taking notes, I'm grateful @evereq

**Comment by evereq** [comment]
And no, feature is not correct exactly be because naming is wrong... you added isStoreMode to Admin user entity.... like user can have a name and also user can have a store mode....
You added it also to warehouse which is correct, because merchant can have in-store mode enabled or disabled @sunk0

**Comment by sunk0** [comment]
Then from where the user should disable all stores, that's the place i thought so?  @evereq

**Pull request closed without merging**
