### PR TITLE
feat: new order popup translation

### PR DESCRIPTION
**Pull request by YavorGrancharov**
-   [x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x] Have you explained what your changes do, and why they add value?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

---
New order popup message translation.
W9lkVbaZO2

### CODE REVIEW

**Comment by evereq** [comment]
@YavorGrancharov on your video, we see that some tabs / other elements do not have a text on them, it's a bug, right? If so, did you report them / find that it's already reported or not? If you did not report, why you did not fix such issues? I.e. how you demonstrate some feature, see it does not work, and did not mention here such issues?

**Comment by YavorGrancharov** [comment]
Yes I saw that ion-icon are not showing on those tabs and tried to get
problem solved, but for what I read it has something to do with ionicons
build or ionic update! I reinstalled node_modules and the issue is still
there. I will open an issue and solve it.

На нд, 26.04.2020 г. в 11:24 Ruslan Konviser <notifications@github.com>
написа:

**Comment by evereq** [comment]
@YavorGrancharov create an issue and assign it to @suryasingh, please. 
Also, next time when you see something not working as it should, please always fix it OR create an issue in Github, don't just ignore it if you can't fix it, etc :)

**Comment by YavorGrancharov** [comment]
Ok, will create an issue.

На нд, 26.04.2020 г., 22:42 Ruslan Konviser <notifications@github.com>
написа:

**Pull request merged**
