### PR TITLE
feat: implemented when the order is confirmed carrier to see all prods

### PR DESCRIPTION
**Pull request by sunk0**
products

### CODE REVIEW

**Comment by sunk0** [comment]
UI-carrier

**Comment by sunk0** [comment]
heCE9x5a2q

**Comment by sunk0** [comment]
carrier-padding

**Comment by evereq** [comment]
@sunk0 yeah, that looks way better than before! Question: that slider we use, maybe it supports some controls like "dots" which give customer idea that there can be more images and it's slider, not a single image? You know like on Desktop, you have arrows to previous / next and say 3 dots?

**Pull request merged**
