### PR TITLE
feat: added new functionality for getting terms from db

### PR DESCRIPTION
**Pull request by sunk0**
So there is a problem with getting the build path.
path-build-problem

### CODE REVIEW

**Comment by sunk0** [comment]
The point is to get terms of use based on language on merchant app

**Comment by sunk0** [comment]
OfUIO15iqg

**Comment by evereq** [comment]
@sunk0 so you make it work now right? At least on carrier/merchant? If so, can you fix it in customer ordering app the same way and clean up code so we merge?

**Comment by sunk0** [comment]
@evereq done

**Pull request merged**
