### PR TITLE
Feat/#30 show orders by status

### PR DESCRIPTION
**Pull request by YavorGrancharov**
-   [x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x] Have you explained what your changes do, and why they add value?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

---
Finished implementing dropdown filter order statuses on Merchant -> Dashboard
Diceded to use interface="popover" on ion-select element because without that option the popever has only first five elements visisble and the user has to scroll over the popup in order to see the rest of the options which is realy counter-intuitive. Now the whole poover shows whole options list, we don't have to translate Cancel and Ok buttons inside code and also user doesn't have to click on radio button and then confirm.
https://www.loom.com/share/bd0fcb9dd3ac4e028710712a65e2026b

### CODE REVIEW

**Comment by YavorGrancharov** [comment]
Progress so far
https://www.loom.com/share/ca73e5bdf9574d79a8ed825cf77b65ae

**Comment by YavorGrancharov** [comment]
via Hubstaff
User: Yavor Grancharov

Project: Ever Platform - https://app.hubstaff.com/projects/1101750
Date Range: 07/09/20 - 07/09/20
Work session total: 6:01:57
Billable: No

Grand total: 6:01:57

**Comment by evereq** [comment]
@YavorGrancharov is it done now?
Things to improve:
- dropdown looks terrible, you need to fix the design of it (color, padding, etc)
- the order of items in the dropdown is wrong. I listed order of statuses, it should be like "Relevant" (default), "All" and next go all other statuses.

**Comment by YavorGrancharov** [comment]
I will take care of all that just needed to be sure that I am doing things
right that is why I requested a review!

На пт, 10.07.2020 г., 17:27 Ruslan Konviser <notifications@github.com>
написа:

**Comment by YavorGrancharov** [comment]
via Hubstaff
User: Yavor Grancharov

Project: Ever Platform - https://app.hubstaff.com/projects/1101750
Date Range: 07/09/20 - 07/09/20
Work session total: 0:15:12
Billable: No

Grand total: 6:17:09

**Pull request merged**
